### PR TITLE
 Add Github Action Compile fix gameserver

### PR DESCRIPTION
**Pull request by tathaha**
[I write this to complie the file on github action](https://github.com/WeedwackerPS/Weedwacker/pull/10)

### CODE REVIEW

**Comment by akatatsu27** [comment]
Seeing as you keep adding commits, I suggest you convert to draft, and request a review when done.

**Comment by Hartie95** [comment]
not sure how different github workflows are compared to gitlab ci tasks, but wouldn't it be better to split them apart in different stages, like build, tests and deploy, where the deploy tasks would only get triggered manually?

**Comment by phuchptty** [comment]
> not sure how different github workflows are compared to gitlab ci tasks, but wouldn't it be better to split them apart in different stages, like build, tests and deploy, where the deploy tasks would only get triggered manually?

it's the same flow. Build should run on every commit or pull request to check buildable. Also, publish should trigger when you manually create a new tag/release

**Comment by Arikatsu** [comment]
To me it feels like you are struggling with this so here's an example
You can really just make two jobs for Webserver and Gameserver with something like this
```yml
jobs:
    build-webserver:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v2
              with:
                  dotnet-version: 6.0.x

            - name: Install dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build <path to webserver.csproj> --configuration Debug --no-restore

            - name: Upload build
              uses: actions/upload-artifact@v3
              with:
                  name: Webserver
                  path: path/to/webserver/artifact

    build-gameserver:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v2
              with:
                  dotnet-version: 6.0.x

            - name: Install dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build <path to gameserver.csproj> --configuration Debug --no-restore

            - name: Upload build
              uses: actions/upload-artifact@v3
              with:
                  name: Webserver
                  path: path/to/gameserverr/artifact
 ```
 This will also upload the the builds as an artifact on the actions page
 
Though microsoft recommends using a docker container to build projects on github actions that are not javascript/typescript. The Dockerfile goes in the root of the repo.


(I came up with this on the fly, point it out if there's anything wrong)

**Pull request closed without merging**
